### ISSUE TITLE
Lupka powinna mieć obramowanie

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/watchdog-kj-kultura#47]
Hej,

Obecnie lupka powiększania grafik nie ma żadnego obramowania. Natomiast grafiki mają jednolite tło. To oznacza, że nie widać granicy między powiększeniem, a grafiką. Proponuje dodać delikatne obramowanie przez coś jak (to działa):

```css
.loupe {
    border: 1px white solid;
}
```
